#!/usr/bin/env bash
#Bash script that install a new Ubuntu Machine
sudo apt-get update
sudo apt-get -y install nginx
sudo chmod r+w /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo services nginx restart
