#!/usr/bin/env bash
# Bash script that Install and configure HAproxy on your lb-01 server.
sudo apt-get update && apt-get upgrade
sudo apt-get install -y haproxy
sudo chmod 666 /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/haproxy/haproxy.cfg
sudo echo "listen test
    bind 0.0.0.0:80
    balance roundrobin
    server 2549-web-01 35.243.232.238:80 check
    server 2549-web-02 35.237.104.223:80 check" | tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
