#!/usr/bin/env bash
#display 10 times Holberton School

for i in {1..100}
do
    if [ $(( i % 15 )) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $(( i % 5 )) -eq 0 ]
    then
	echo "Buzz"
    elif [ $(( i % 3 )) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
