#!/usr/bin/env bash
#display 10 times Holberton School

i=1

while ((i++ < 10))
do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
        ((i++))
    fi

    if [ "$i" -eq 8 ]
    then
        echo "good luck"
        ((i++))
    fi

    echo "Holberton School"
done
