#!/usr/bin/env bash
#display 10 times Holberton School

i=0
j=1

echo "Hour: $i"

while (("i" < 12))
do
    j=1
    while (("j" < 60))
    do
        echo $j
        ((j++))
    done
    ((i++))
    echo "Hour: $i"
done
