#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01

sudo apt-get update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw enable
