#!/usr/bin/env bash
# Nginx is running as the nginx user and listening on all active IPs on port 8080

sudo chmod 666 /etc/nginx/sites-available/default
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
